package database

type OnReachMaxWarningsPerUserType int8

const (
	ON_REACH_MAX_WARNINGS_PER_USER_BAN OnReachMaxWarningsPerUserType = iota
	ON_REACH_MAX_WARNINGS_PER_USER_KICK
	ON_REACH_MAX_WARNINGS_PER_USER_GIVE_ROLE
)
