// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Guild struct {
	ID                                                  string
	MaxWarningsPerUser                                  pgtype.Int4
	OnReachMaxWarningsPerUser                           pgtype.Int4
	SecondsToDeleteMessagesForOnReachMaxWarningsPerUser pgtype.Int4
	RoleToGiveOnReachMaxWarningsPerUser                 pgtype.Text
	SecondsWarnedUserShouldKeepRoleFor                  pgtype.Int4
}

type GuildMember struct {
	UserID   string
	GuildID  string
	Warnings pgtype.Int4
}
