// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Guild struct {
	ID                 string
	MaxWarningsPerUser pgtype.Int4
}

type WarnedUser struct {
	GuildID  string
	UserID   string
	Warnings pgtype.Int4
}
