// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (id) VALUES ($1) RETURNING id, max_warnings_per_user
`

func (q *Queries) CreateGuild(ctx context.Context, id string) (Guild, error) {
	row := q.db.QueryRow(ctx, createGuild, id)
	var i Guild
	err := row.Scan(&i.ID, &i.MaxWarningsPerUser)
	return i, err
}

const createGuildMember = `-- name: CreateGuildMember :one
INSERT INTO guild_members (guild_id, user_id) VALUES ($1, $2) RETURNING warnings
`

type CreateGuildMemberParams struct {
	GuildID string
	UserID  string
}

func (q *Queries) CreateGuildMember(ctx context.Context, arg CreateGuildMemberParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, createGuildMember, arg.GuildID, arg.UserID)
	var warnings pgtype.Int4
	err := row.Scan(&warnings)
	return warnings, err
}

const getGuild = `-- name: GetGuild :one
SELECT
    id, max_warnings_per_user
FROM
    guilds
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetGuild(ctx context.Context, id string) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i Guild
	err := row.Scan(&i.ID, &i.MaxWarningsPerUser)
	return i, err
}

const getWarningsFromGuildMember = `-- name: GetWarningsFromGuildMember :one
SELECT warnings FROM guild_members WHERE guild_id = $1 AND user_id = $2 LIMIT 1
`

type GetWarningsFromGuildMemberParams struct {
	GuildID string
	UserID  string
}

func (q *Queries) GetWarningsFromGuildMember(ctx context.Context, arg GetWarningsFromGuildMemberParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getWarningsFromGuildMember, arg.GuildID, arg.UserID)
	var warnings pgtype.Int4
	err := row.Scan(&warnings)
	return warnings, err
}

const updateGuildMemberWarnings = `-- name: UpdateGuildMemberWarnings :exec
UPDATE guild_members SET warnings = $1 WHERE guild_id = $2 AND user_id = $3
`

type UpdateGuildMemberWarningsParams struct {
	Warnings pgtype.Int4
	GuildID  string
	UserID   string
}

func (q *Queries) UpdateGuildMemberWarnings(ctx context.Context, arg UpdateGuildMemberWarningsParams) error {
	_, err := q.db.Exec(ctx, updateGuildMemberWarnings, arg.Warnings, arg.GuildID, arg.UserID)
	return err
}
