package config

import (
	"os"
)

var (
	DEVELOPMENT_POSTGRESQL_CONNECTION_STRING string
	POSTGRESQL_CONNECTION_STRING             string
)

func Load() {
	DEVELOPMENT_POSTGRESQL_CONNECTION_STRING = os.Getenv("DEVELOPMENT_POSTGRESQL_CONNECTION_STRING")
	POSTGRESQL_CONNECTION_STRING = os.Getenv("POSTGRESQL_CONNECTION_STRING")
}
