package tools

import (
	"slices"

	bot_types "presto/internal/bot/types"
)

// Compares two application commands without taking the ID into consideration.
// This is because registered commands are structs created with the necessary data
// to create or update an application command and the ID is generated by Discord so
// every comparision using `reflect.DeepEqual` would fail since the command registered locally
// will have `nil` as the ID while the application command fetched from Discord will have some
// snowflake as the ID. `ApplicationCommand.Handler` is also ignored.
func CompareApplicationCommands(a bot_types.ApplicationCommand, b bot_types.ApplicationCommand) bool {
	return a.Name == b.Name && a.Description == b.Description && a.Type == b.Type && slices.Equal(a.Options, b.Options)
}
